const os = require('os');
console.log(os.totalmem());
console.log(os.uptime());
console.log(os.arch());
console.log(os.type());
console.log(os.platform());
console.log(os.hostname());
console.log(os.homedir());
console.log(os.freemem());
console.log(os.availableParallelism());
console.log(os.getPriority());
console.log(os.loadavg());
console.log(os.networkInterfaces());
console.log(os.userInfo());